<?php


namespace Tests;


use App\Creational\Pool\Car;
use App\Creational\Pool\CarPool;
use PHPUnit\Framework\TestCase;

class PoolTest extends TestCase
{

    /**
     * @var CarPool
     */
    private CarPool $carPool;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->carPool = new CarPool();
    }

    /**
     * @test
     */
    public function testCanRentCar()
    {
        $myCar = $this->carPool->rentCar();
        $this->assertInstanceOf(Car::class,$myCar);
        $this->assertEquals(1,$this->carPool->getAllCarsCount());
        return $myCar;
    }

    /**
     * @test
     */
    public function testCanFreeCar()
    {
        // check if have 1 car ib busy state
        $myCar = $this->testCanRentCar();
        $this->assertEquals(1,$this->carPool->getBusyCarsCount());
        // check
        $this->carPool->freeCar($myCar);
        $this->assertEquals(0,$this->carPool->getBusyCarsCount());
    }
}